# Generated by Django 3.2.4 on 2021-06-08 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoría')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de la categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Producto')),
                ('nombreProducto', models.CharField(max_length=100, verbose_name='Nombre del producto')),
                ('descripcionProducto', models.CharField(max_length=200, verbose_name='Descripción del producto')),
                ('imgProducto', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Imagen del producto')),
                ('precioProducto', models.IntegerField(verbose_name='Precio del producto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
